plugins {
    id "com.android.application"
}

android {
    namespace "com.ximbica.xlite"
    compileSdk {
        version = release(37) {
            minorApiLevel = 2
        }
    }

    defaultConfig {
        applicationId "com.ximbica.xlite"
        minSdk 26
        targetSdk 35
        versionCode 2
        versionName "0.2.0"
        manifestPlaceholders = [geckoViewChannel: "release"]

        ndk {
            abiFilters "armeabi-v7a"
        }
    }

    buildTypes {
        debug {
            minifyEnabled false
        }
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro"
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    packaging {
        resources {
            excludes += [
                "META-INF/DEPENDENCIES",
                "META-INF/LICENSE*",
                "META-INF/NOTICE*"
            ]
        }
    }
}

dependencies {
    implementation "org.mozilla.geckoview:geckoview:155.0.20260903215306"
}
